/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pol_D
 */
public class Cursos extends javax.swing.JFrame {

  /**
   * Creates new form Cursos
   */
  public Cursos() {
    initComponents();
    cargarCmbCatiCreditos ();
    cargarCmbHorasLectivas ();
    obtenerNombreEscuela ();
  }
  
  public void cargarCmbCatiCreditos () {
    for(int inicial = 1; inicial < 11; inicial++) {
      String numCadena= inicial+"";
      comBxCantiCreditos.addItem(numCadena );
    }
  }
  
  public void cargarCmbHorasLectivas () {
    for(int inicial = 1; inicial < 25; inicial++) {
      String numCadena= inicial+"";
    comBxHorasLectivas.addItem(numCadena );
    }
  }
  
  public void obtenerNombreEscuela () {
    ResultSet rs;
    try {
      DefaultComboBoxModel listaModelo = new DefaultComboBoxModel();
      listaModelo.addElement("Selecciones una clave");
    
      Connection connect = DriverManager.getConnection("jdbc:sqlserver://;databaseName=Proyecto_POO1;user=usuariosql;password=root1");
      PreparedStatement st = connect.prepareStatement("SELECT * from EscuelaOArea order by nombreCarrera");
      rs = st.executeQuery();
    
      try {
        while (rs.next()){
          listaModelo.addElement(rs.getString("nombreCarrera"));
      } rs.close();
      
      } catch(SQLException ex ){
        System.err.println(ex.getMessage());
      } comBxEscuelaOAreaCargo.setModel(listaModelo);
    } catch(SQLException e){
      JOptionPane.showMessageDialog(null,e);
    }
  }
  
  public void cargarCantidadCursos () {
    ResultSet rs;
    try {
      Connection connect = DriverManager.getConnection("jdbc:sqlserver://;databaseName=Proyecto_POO1;user=usuariosql;password=root1");
      PreparedStatement st = connect.prepareStatement("SELECT COUNT (*) AS cantidadCursos FROM Curso");
      rs = st.executeQuery();
    
      try {
        if(rs.next()) {
       //Si hay resultados obtengo el valor. 
        this.cantidadCursos= rs.getInt(1);
     } rs.close();
      
      } catch(SQLException ex ){
        System.err.println(ex.getMessage());
      }
    } catch(SQLException e){
      JOptionPane.showMessageDialog(null,e);
    }
  }
  
  
  public String generarCodigoCurso (String pNombreEscuela ){
    int largo = pNombreEscuela.length();
    String ini=" ";
    String xx=pNombreEscuela.substring(0, 1);;
    String x="";
    String xxx="";
        for (int i = 0; i <largo; i++) {
            x=pNombreEscuela.substring(i,i+1);
        
          if (x.equals(ini)) {
             
              xxx=pNombreEscuela.substring(i+1, i+2);
                xx=xx+xxx+this.cantidadCursos;
                
            } 
            
        }
    return xx;
  }
  public String generarCodigoEscuelaCurso (String pNombreEscuela ){
    int largo = pNombreEscuela.length();
    String ini=" ";
    String xx=pNombreEscuela.substring(0, 1);;
    String x="";
    String xxx="";
    for (int i = 0; i <largo; i++) {
        x=pNombreEscuela.substring(i,i+1);
      if (x.equals(ini)) {
        xxx=pNombreEscuela.substring(i+1, i+2);
        xx=xx+xxx;

      } 
    }
    return xx;
  }
  
  
  public void cargarCmbNombreEscuelas (){}

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblCursos = new javax.swing.JTable();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    comBxEscuelaOAreaCargo = new javax.swing.JComboBox<>();
    txtNombreCurso = new javax.swing.JTextField();
    comBxCantiCreditos = new javax.swing.JComboBox<>();
    comBxHorasLectivas = new javax.swing.JComboBox<>();
    btnGuardarCurso = new javax.swing.JButton();
    btnLimpiarCurso = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Cursos");

    jLabel1.setText("Registro de cursos");

    jLabel2.setText("Escuela o área propietaria del curso:");

    tblCursos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null}
      },
      new String [] {
        "Código", "Nombre", "Escuela o área a cargo", "Créditos", "Horas lectivas"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, true, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tblCursos);

    jLabel4.setText("Nombre del curso:");

    jLabel5.setText("Cantidad de créditos:");

    jLabel6.setText("Horas lectivas:");

    comBxEscuelaOAreaCargo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comBxEscuelaOAreaCargoActionPerformed(evt);
      }
    });

    btnGuardarCurso.setText("Guardar");
    btnGuardarCurso.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarCursoActionPerformed(evt);
      }
    });

    btnLimpiarCurso.setText("Limpiar");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(btnGuardarCurso)
                .addGap(100, 100, 100)
                .addComponent(btnLimpiarCurso))))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel6)
              .addComponent(jLabel5)
              .addComponent(jLabel4)
              .addComponent(jLabel2))
            .addGap(50, 50, 50)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(comBxEscuelaOAreaCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(txtNombreCurso)
              .addComponent(comBxCantiCreditos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(comBxHorasLectivas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap(43, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(40, 40, 40)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(comBxEscuelaOAreaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(23, 23, 23)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(29, 29, 29)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(comBxCantiCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(comBxHorasLectivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnGuardarCurso)
          .addComponent(btnLimpiarCurso))
        .addGap(27, 27, 27)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(74, 74, 74))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void comBxEscuelaOAreaCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBxEscuelaOAreaCargoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_comBxEscuelaOAreaCargoActionPerformed

  private void btnGuardarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCursoActionPerformed
      String escuelaIng = comBxEscuelaOAreaCargo.getSelectedItem().toString();
      String codigoEscuelaIng = generarCodigoEscuelaCurso (escuelaIng );
      
      String codigoCursoIng = generarCodigoCurso (escuelaIng );
      String nombreCursoIng = txtNombreCurso.getText();
      int cantidadCreditosIng = Integer.parseInt(comBxCantiCreditos.getSelectedItem().toString());
      int horasLectivasIng =  Integer.parseInt(comBxHorasLectivas.getSelectedItem().toString());
      this.cantidadCursos++;
      
    try {
      Connection connect = DriverManager.getConnection("jdbc:sqlserver://;databaseName=Proyecto_POO1;user=usuariosql;password=root1");
      PreparedStatement st = connect.prepareStatement("INSERT INTO Curso VALUES ('"+ codigoCursoIng + ","+ "','"+ nombreCursoIng +"',"+ cantidadCreditosIng +", "+ horasLectivasIng +", "+ cantidadCursos +")");
      st.executeUpdate();
      JOptionPane.showMessageDialog(null,"Registro guardado");
      //limpiar();
      //cargarTabla();
      //c.close();
    } 
    catch (SQLException ex) {
     System.err.println(ex.getMessage());
    }
    
    try {
      Connection connect = DriverManager.getConnection("jdbc:sqlserver://;databaseName=Proyecto_POO1;user=usuariosql;password=root1");
      PreparedStatement st = connect.prepareStatement("INSERT INTO CursosPorEscuela VALUES ('"+ codigoEscuelaIng + ","+ "','"+ codigoCursoIng +"')");
      st.executeUpdate();
      JOptionPane.showMessageDialog(null,"Registro guardado");
      //limpiar();
      //cargarTabla();
      //c.close();
    } 
    catch (SQLException ex) {
     System.err.println(ex.getMessage());
    } 
    
  }//GEN-LAST:event_btnGuardarCursoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Cursos().setVisible(true);
      }
    });
  }
  
  private int cantidadCursos; 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnGuardarCurso;
  private javax.swing.JButton btnLimpiarCurso;
  private javax.swing.JComboBox<String> comBxCantiCreditos;
  private javax.swing.JComboBox<String> comBxEscuelaOAreaCargo;
  private javax.swing.JComboBox<String> comBxHorasLectivas;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblCursos;
  private javax.swing.JTextField txtNombreCurso;
  // End of variables declaration//GEN-END:variables
}
