/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion;

/**
 *
 * @author farol
 */
public class Menu extends javax.swing.JFrame {

  /**
   * Creates new form Menu
   */
  public Menu() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    btnConsulta4 = new javax.swing.JButton();
    btnConsulta3 = new javax.swing.JButton();
    btnCursos = new javax.swing.JButton();
    btnEscuela = new javax.swing.JButton();
    btnRequisitos = new javax.swing.JButton();
    btnConsulta1 = new javax.swing.JButton();
    btnPlanes = new javax.swing.JButton();
    btnConsulta2 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 74, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 57, Short.MAX_VALUE)
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jPanel2.setBackground(new java.awt.Color(0, 0, 153));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Menú principal");

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Proyecto 1 de Programación Orientada a Objetos");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(375, 375, 375))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(428, 428, 428))))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(jLabel2)
        .addContainerGap(29, Short.MAX_VALUE))
    );

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel3.setText("¿Qué desea hacer?");

    btnConsulta4.setBackground(new java.awt.Color(153, 204, 255));
    btnConsulta4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnConsulta4.setText("Consultar Correquisitos");
    btnConsulta4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsulta4ActionPerformed(evt);
      }
    });

    btnConsulta3.setBackground(new java.awt.Color(153, 204, 255));
    btnConsulta3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnConsulta3.setText("Consultar Requisitos");
    btnConsulta3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsulta3ActionPerformed(evt);
      }
    });

    btnCursos.setBackground(new java.awt.Color(153, 204, 255));
    btnCursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnCursos.setText("Registrar Cursos");
    btnCursos.setMaximumSize(new java.awt.Dimension(201, 23));
    btnCursos.setMinimumSize(new java.awt.Dimension(201, 23));
    btnCursos.setPreferredSize(new java.awt.Dimension(201, 23));
    btnCursos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCursosActionPerformed(evt);
      }
    });

    btnEscuela.setBackground(new java.awt.Color(153, 204, 255));
    btnEscuela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnEscuela.setText("Registrar Escuela o Área");
    btnEscuela.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEscuelaActionPerformed(evt);
      }
    });

    btnRequisitos.setBackground(new java.awt.Color(153, 204, 255));
    btnRequisitos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnRequisitos.setText("Asignar Requisitos y Correquisitos");
    btnRequisitos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRequisitosActionPerformed(evt);
      }
    });

    btnConsulta1.setBackground(new java.awt.Color(153, 204, 255));
    btnConsulta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnConsulta1.setText("Consultar Plan de Estudio");
    btnConsulta1.setMaximumSize(new java.awt.Dimension(201, 23));
    btnConsulta1.setMinimumSize(new java.awt.Dimension(201, 23));
    btnConsulta1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsulta1ActionPerformed(evt);
      }
    });

    btnPlanes.setBackground(new java.awt.Color(153, 204, 255));
    btnPlanes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnPlanes.setText("Registrar Plan de Estudio");
    btnPlanes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPlanesActionPerformed(evt);
      }
    });

    btnConsulta2.setBackground(new java.awt.Color(153, 204, 255));
    btnConsulta2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btnConsulta2.setText("Consultar Plan de Curso particular");
    btnConsulta2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsulta2ActionPerformed(evt);
      }
    });

    jLabel4.setText("Elaborado por: Josué Brenes, Paola Lopez, Alejandra Merino");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnConsulta3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(187, 187, 187)
        .addComponent(btnConsulta4)
        .addGap(217, 217, 217))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(70, 70, 70)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(btnEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(85, 85, 85)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnConsulta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnRequisitos, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(40, 40, 40))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addComponent(jLabel4))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel3)
        .addGap(27, 27, 27)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(36, 36, 36)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(59, 59, 59)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnConsulta4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnConsulta3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
        .addComponent(jLabel4)
        .addContainerGap())
    );

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 470));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnConsulta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta4ActionPerformed
    ConsultaCorequisitos verConsultaCorequisitos = new ConsultaCorequisitos();    
    verConsultaCorequisitos.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_btnConsulta4ActionPerformed

  private void btnConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta3ActionPerformed
    ConsultaRequisitos verConsultaRequisitos = new ConsultaRequisitos();    
    verConsultaRequisitos.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_btnConsulta3ActionPerformed

  private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
    Cursos verCursos = new Cursos();    
    verCursos.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_btnCursosActionPerformed

  private void btnEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscuelaActionPerformed
    Escuela verEscuela = new Escuela();    
    verEscuela.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_btnEscuelaActionPerformed

  private void btnRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequisitosActionPerformed
    RegistroRequisitos verRequisitos = new RegistroRequisitos();    
    verRequisitos.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_btnRequisitosActionPerformed

  private void btnConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta1ActionPerformed
    Consulta1 verConsulta1 = new Consulta1();    
    verConsulta1.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_btnConsulta1ActionPerformed

  private void btnPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanesActionPerformed
    RegistroPlanesEstudio verRegistroPlanesEstudio = new RegistroPlanesEstudio();    
    verRegistroPlanesEstudio.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_btnPlanesActionPerformed

  private void btnConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta2ActionPerformed
    Consulta2 verConsulta2 = new Consulta2();    
    verConsulta2.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_btnConsulta2ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Menu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnConsulta1;
  private javax.swing.JButton btnConsulta2;
  private javax.swing.JButton btnConsulta3;
  private javax.swing.JButton btnConsulta4;
  private javax.swing.JButton btnCursos;
  private javax.swing.JButton btnEscuela;
  private javax.swing.JButton btnPlanes;
  private javax.swing.JButton btnRequisitos;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  // End of variables declaration//GEN-END:variables
}
